// DASHBOARD
const ADD_TO_DASH = 'ADD_TO_DASH';
const ADD_TO_USER_DASH = 'ADD_TO_USER_DASH';
const GET_DASH = 'GET_DASH';
const REM_FROM_DASH = 'REM_FROM_DASH';
const ADD_DISPLAY_DASH_ITEM = 'DISPLAY_DASH_ITEM';

// USERS
const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

// DND API
const GET_MONSTERS = 'GET_MONSTERS';
const GET_SPELLS = 'GET_SPELLS';
const GET_EQUIPMENT = 'GET_EQUIPMENT';

// EQUIPMENT 
const CREATE_EQUIP = 'CREATE_EQUIP';
const GET_USER_EQUIP = 'GET_USER_EQUIP';
const EDIT_USER_EQUIP = 'EDIT_USER_EQUIP';
const REM_USER_EQUIP = 'REM_USER_EQUIP';

// MOUNTS
const CREATE_MOUNT = 'CREATE_MOUNT';
const GET_USER_MOUNT = 'GET_USER_MOUNT';
const EDIT_USER_MOUNT = 'EDIT_USER_MOUNT';
const REM_USER_MOUNT = 'REM_USER_MOUNT';

// ARMOR
const CREATE_ARM = 'CREATE_ARM';
const GET_USER_ARM = 'GET_USER_ARM';
const EDIT_USER_ARM = 'EDIT_USER_ARM';
const REM_USER_ARM = 'REM_USER_ARM';
const USER_ARM_DASH = 'USER_ARM_DASH'

// SEARCH

const SEARCH = 'SEARCH';

export default {

    // DASHBOARD

    ADD_TO_DASH,
    ADD_TO_USER_DASH,
    GET_DASH,
    REM_FROM_DASH,
    ADD_DISPLAY_DASH_ITEM,

    // USERS

    UPDATE_USER_INFO,

    // DND API

    GET_MONSTERS,
    GET_SPELLS,
    GET_EQUIPMENT,

    // EQUIPMENT 

    CREATE_EQUIP,
    GET_USER_EQUIP,
    EDIT_USER_EQUIP,
    REM_USER_EQUIP,

    // MOUNTS

    CREATE_MOUNT,
    GET_USER_MOUNT,
    EDIT_USER_MOUNT,
    REM_USER_MOUNT,

    // ARMOR

    CREATE_ARM,
    GET_USER_ARM,
    EDIT_USER_ARM,
    REM_USER_ARM,
    USER_ARM_DASH,

    // SEARCH

    SEARCH
}